---
global:
  extraEnvVars:
    - name: LOG_LEVEL
      value: debug
    - name: SESSION_SECRET
      value: "Eq9AIhWdD0uxWVSv5pmtTPVipZt/c9Q6GZqnQNhX5BE="
    - name: SESSION_COOKIE_DOMAIN
      value: "example.com"

hub:
  extraEnvVars:
    - name: OIDC_CLIENT_ID
      value: ""
    - name: OIDC_CLIENT_SECRET
      value: ""
    - name: OIDC_ISSUER
      value: ""
    - name: OIDC_REDIRECT_URI
      value: ""
    - name: OIDC_JWKS_URI
      value: ""
    - name: OIDC_AUDIENCE
      value: ""
    - name: OIDC_POST_LOGOUT_REDIRECT_URI
      value: ""

auth:
  extraEnvVars:
    - name: OIDC_CLIENT_ID
      value: ""
    - name: OIDC_CLIENT_SECRET
      value: ""
    - name: OIDC_ISSUER
      value: ""
    - name: OIDC_REDIRECT_URI
      value: ""
    - name: OIDC_JWKS_URI
      value: ""
    - name: OIDC_AUDIENCE
      value: ""
    - name: OIDC_POST_LOGOUT_REDIRECT_URI
      value: ""

ingress:
  annotations:
    kubernetes.io/ingress.global-static-ip-name: mcpx-lunar-mcpx-webapp
  type: gce

  domains:
    webserver:
      - mcpx-app.example.com
    admin:
      - mcpx-admin.example.com
    auth:
      - mcpx-auth.example.com

postgres:
  enabled: true

redis:
  enabled: true
