apiVersion: v2
name: mcpx-hive
description: A comprehensive Helm chart for the MCPx Hive system including hive-controller and ingress
type: application
version: 0.1.0
appVersion: "0.1.0"
maintainers:
  - name: Lunar Team
    email: support@lunar.dev
icon: https://storage.googleapis.com/lunar-webapp-assets/favicon/apple-touch-icon.png
