apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mcpx-hive.controller.fullname" . }}-token
  labels:
    {{- include "mcpx-hive.controller.labels" . | nindent 4 }}
type: Opaque
stringData:
  controller-token: {{ .Values.hiveController.controllerToken | default (randAlphaNum 32) | quote }}
