{{- $defaults := fromYaml (.Files.Get "internal-values.yaml") -}}
{{- $values := mergeOverwrite (deepCopy $defaults) .Values -}}
{{- $ctx := dict "Values" $values "Chart" .Chart "Release" .Release "Capabilities" .Capabilities "Files" .Files "Template" .Template "Subcharts" .Subcharts -}}
{{- with $ctx }}
{{- if .Values.hiveController.serviceAccount.create | default true }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mcpx-hive.controller.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mcpx-hive.controller.labels" . | nindent 4 }}
  {{- with .Values.hiveController.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
