{{- if .Values.hiveController.serviceAccount.create | default true }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mcpx-hive.hive-controller.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mcpx-hive.hive-controller.labels" . | nindent 4 }}
  {{- with .Values.hiveController.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}


