apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "lunar-mcpx.fullname" . }}-config
data:
  mcp.json: |
{{ .Values.config.mcpJson | indent 4 }}
  app.yaml: |
{{ .Values.config.appYaml | indent 4 }}
