apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lunar-mcpx.fullname" . }}
  labels:
    app: {{ include "lunar-mcpx.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "lunar-mcpx.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "lunar-mcpx.fullname" . }}
    spec:
      containers:
        - name: mcpx
          image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}

          {{- with .Values.healthcheck }}
          {{- if .readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .path }}
              port: {{ .Values.service.port }}
            initialDelaySeconds: {{ .readinessProbe.initialDelaySeconds }}
            periodSeconds:      {{ .readinessProbe.periodSeconds }}
            timeoutSeconds:     {{ .readinessProbe.timeoutSeconds }}
            failureThreshold:   {{ .readinessProbe.failureThreshold }}
            successThreshold:   {{ .readinessProbe.successThreshold }}
          {{- end }}

          {{- if .livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .path }}
              port: {{ .Values.service.port }}
            initialDelaySeconds: {{ .livenessProbe.initialDelaySeconds }}
            periodSeconds:      {{ .livenessProbe.periodSeconds }}
            timeoutSeconds:     {{ .livenessProbe.timeoutSeconds }}
            failureThreshold:   {{ .livenessProbe.failureThreshold }}
          {{- end }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: mcp-config-vol
              mountPath: /etc/lunar-mcpx
              readOnly: true
          env:
          {{- if .Values.secretRef }}
            {{- range .Values.secretRef.keys }}
            - name: {{ . }}
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.secretRef.name }}
                  key: {{ . }}
            {{- end }}
          {{- end }}
            - name: MCPX_PORT
              value: {{ .Values.service.port | quote }}
            - name: LUNAR_URL
              value: {{ .Values.lunarURL }}
            - name: SERVERS_CONFIG_PATH
              value: /etc/lunar-mcpx/mcp.json
            - name: APP_CONFIG_PATH
              value: /etc/lunar-mcpx/app.yaml
            - name: LOG_LEVEL
              value: {{ .Values.logLevel }}
            - name: ENABLE_METRICS
              value: {{ .Values.metrics.enabled | quote }}
            - name: SERVE_METRICS_PORT
              value: {{ .Values.metrics.port | quote }}
            - name: DIND_ENABLED
              value: {{ .Values.dockerInDocker.enabled | quote }}
            - name: ENABLE_CONTROL_PLANE_STREAMING
              value: {{ .Values.controlPlane.streaming.enabled | quote }}
            - name: ENABLE_CONTROL_PLANE_REST
              value: {{ .Values.controlPlane.rest.enabled | quote }}
            - name: WEBSERVER_URL
              value: {{ .Values.controlPlane.host }}
          
      volumes:
        - name: mcp-config-vol
          configMap:
            name: {{ include "lunar-mcpx.fullname" . }}-config
