apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lunar-mcpx.fullname" . }}
  labels:
    app: {{ include "lunar-mcpx.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "lunar-mcpx.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "lunar-mcpx.fullname" . }}
    spec:
      containers:
        - name: mcpx
          image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 9000

          {{- with .Values.healthcheck }}
          {{- if .readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .path }}
              port: http
            initialDelaySeconds: {{ .readinessProbe.initialDelaySeconds }}
            periodSeconds:      {{ .readinessProbe.periodSeconds }}
            timeoutSeconds:     {{ .readinessProbe.timeoutSeconds }}
            failureThreshold:   {{ .readinessProbe.failureThreshold }}
            successThreshold:   {{ .readinessProbe.successThreshold }}
          {{- end }}

          {{- if .livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .path }}
              port: http
            initialDelaySeconds: {{ .livenessProbe.initialDelaySeconds }}
            periodSeconds:      {{ .livenessProbe.periodSeconds }}
            timeoutSeconds:     {{ .livenessProbe.timeoutSeconds }}
            failureThreshold:   {{ .livenessProbe.failureThreshold }}
          {{- end }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: mcp-config-vol
              mountPath: /config
              readOnly: true
          env:
          {{- if .Values.secretRef }}
            {{- range .Values.secretRef.keys }}
            - name: {{ . }}
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.secretRef.name }}
                  key: {{ . }}
            {{- end }}
          {{- end }}
      volumes:
        - name: mcp-config-vol
          configMap:
            name: {{ include "lunar-mcpx.fullname" . }}-config
