---
OIDC_CLIENT_ID: string
OIDC_CLIENT_SECRET: string
OIDC_EMAIL_CLAIM: string
OIDC_ISSUER: string
OIDC_POST_LOGOUT_REDIRECT_URI: string
OIDC_REDIRECT_URI: string
OIDC_ROLES_CLAIM: string
OIDC_SCOPES: string
