{{- $defaults := fromYaml (.Files.Get "internal-values.yaml") -}}
{{- $values := mergeOverwrite (deepCopy $defaults) .Values -}}
{{- $ctx := dict "Values" $values "Chart" .Chart "Release" .Release "Capabilities" .Capabilities "Files" .Files "Template" .Template "Subcharts" .Subcharts -}}
{{- with $ctx }}
{{- if .Values.global.redis.deploy }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mcpx-hive.name" . }}-redis
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "mcpx-hive.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: redis
    app.kubernetes.io/part-of: {{ include "mcpx-hive.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.redis.service.type }}
  ports:
    - name: redis
      port: {{ .Values.redis.service.port }}
      targetPort: 6379
  selector:
    app.kubernetes.io/name: {{ include "mcpx-hive.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: redis
{{- end }}
{{- end }}
