{{/*
AWS-specific ingress annotations
*/}}
{{- define "ingress.aws.annotations" -}}
{{- $fullname := include "mcpx-hive.fullname" . }}
kubernetes.io/ingress.class: "alb"
alb.ingress.kubernetes.io/scheme: internet-facing
alb.ingress.kubernetes.io/target-type: ip
{{- if .Values.ingress.aws.loadBalancerName }}
alb.ingress.kubernetes.io/load-balancer-name: {{ .Values.ingress.aws.loadBalancerName }}
{{- end }}
{{- if .Values.ingress.aws.securityGroups }}
alb.ingress.kubernetes.io/security-groups: {{ join "," .Values.ingress.aws.securityGroups }}
{{- end }}
{{- if .Values.ingress.aws.subnets }}
alb.ingress.kubernetes.io/subnets: {{ join "," .Values.ingress.aws.subnets }}
{{- end }}
{{- if .Values.ingress.aws.elasticIPs }}
alb.ingress.kubernetes.io/eip-allocations: {{ join "," .Values.ingress.aws.elasticIPs }}
{{- end }}
{{- if .Values.ingress.aws.certificateArn }}
alb.ingress.kubernetes.io/certificate-arn: {{ .Values.ingress.aws.certificateArn }}
{{- end }}
alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
alb.ingress.kubernetes.io/ssl-redirect: '443'
{{- end }}
