replicaCount: 1

image:
  repository: us-central1-docker.pkg.dev/prj-common-442813/mcpx/mcpx
  tag: ""
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 9000

resources:
  limits:
    cpu: 500m
    memory: 264Mi
  requests:
    cpu: 250m
    memory: 128Mi

healthcheck:
  path: /healthcheck

  # healthcheck.readinessProbe is used to configure the readiness probe for the mcpx deployment.
  readinessProbe:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 1
    failureThreshold: 3
    successThreshold: 1

  # healthcheck.livenessProbe is used to configure the liveness probe for the mcpx deployment.
  livenessProbe:
    enabled: true
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 1
    failureThreshold: 3

# logLevel is the log level for the mcpx deployment.
logLevel: info
lunarURL: "https://hosted-gateway.lunar.dev"

metrics:
  # metrics.enabled is used to enable or disable the metrics server & metrics collections.
  enabled: true
  # metrics.port is the port on which the metrics server will listen.
  port: 3000

dockerInDocker:
  # dockerInDocker.enabled is used to enable or disable the Docker-in-Docker feature, which allows the mcpx deployment to run Docker containers inside the mcpx container.
  enabled: false

config:
  # config.mcpJson supplies content to the `mcp.json` file that contains the target MCP servers configuration.
  mcpJson: |
    {
      "mcpServers": {
        "time": {
          "command": "uvx",
          "args": ["mcp-server-time", "--local-timezone=America/New_York"]
        }
      }
    }

  # config.appYaml supplies content to the `app.yaml` file that contains the application configuration.
  appYaml: |
    auth:
      enabled: false
    permissions:
      base: "allow"
    toolExtensions:
      services: {}


secretRef:
  # secretRef.name is the name of the Kubernetes Secret that contains the sensitive data.
  name: ""
  # secretRef.keys is a list of keys in the Kubernetes Secret that should be made available as environment variables in the mcpx container.
  keys: []

controlPlane:
  host: ""
  streaming:
    enabled: false
  rest:
    enabled: false
