replicaCount: 1

image:
  repository: us-central1-docker.pkg.dev/prj-common-442813/mcpx/mcpx
  tag: ""
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 9000

resources:
  limits:
    cpu: 500m
    memory: 264Mi
  requests:
    cpu: 250m
    memory: 128Mi

healthcheck:
  path: /healthcheck

  readinessProbe:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 1
    failureThreshold: 3
    successThreshold: 1

  livenessProbe:
    enabled: true
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 1
    failureThreshold: 3

logLevel: info

metrics:
  enabled: true
  port: 3000

dockerInDocker:
  enabled: false

controlPlane:
  host: ""
  streaming:
    enabled: false
  rest:
    enabled: false

config:
  mcpJson: |
    {
      "mcpServers": {
        "time": {
          "command": "uvx",
          "args": ["mcp-server-time", "--local-timezone=America/New_York"]
        }
      }
    }

  appYaml: |
    auth:
      enabled: false
    permissions:
      base: "allow"
    toolExtensions:
      services: {}
