name: Proxy Docker Build Push
on:
    repository_dispatch:
      types: [run-action]

jobs:
  helm-chart:
    permissions:
      contents: write
    # needs: docker
    runs-on: ubuntu-22.04
    # if: |
    #   github.event_name == 'push' && contains(github.ref, 'refs/tags/') &&
    #   contains(github.ref, 'lunar-proxy-v')
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config user.name "DevOps"
          git config user.email "devops@lunar.dev"

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Package
        run: |
          VERSION=${{github.ref_name}}
          rm -rf .cr-release-packages
          mkdir -p .cr-release-packages
          helm package "proxy/deploy/k8s/helm-charts" --version 0.8.9 --app-version v0.8.9 --destination=.cr-release-packages

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        with:
          skip_packaging: true
          charts_repo_url: "github.com/TheLunarCompany/public-test"
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_OWNER: LunarDevops
          CR_GIT_REPO: helm-charts

      - name: Trigger Deploy Workflow
        if: ${{ github.event_name != 'release' }} && github.event.action == 'created' && startsWith(github.head_ref, 'refs/tags/v')
        run: |
          gh workflow run 'Rlease Helm-Chart' --repo=TheLunarCompany/helm-chart --ref=gh-pages -f version=${{ github.ref_name }}
        env:
          GH_TOKEN: ${{ secrets.GIT_TOKEN }}