{{- if .Values.llmGateway.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "lunar-mcpx-webapp.fullname" . }}-llm-gateway
  labels:
    name: {{ include "lunar-mcpx-webapp.fullname" . }}-llm-gateway
    app: {{ include "lunar-mcpx-webapp.fullname" . }}-llm-gateway
    {{- with .Values.global.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.llmGateway.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
  selector:
    app: {{ include "lunar-mcpx-webapp.fullname" . }}-llm-gateway
    {{- include "lunar-mcpx-webapp.selectorLabels" . | nindent 4 }}
{{- end }}
