{{- if .Values.webserver.enabled | default true }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "lunar-mcpx-webapp.fullname" . }}-webserver
  labels:
    name: {{ include "lunar-mcpx-webapp.fullname" . }}-webserver
    app: {{ include "lunar-mcpx-webapp.fullname" . }}-webserver
    {{- with .Values.global.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.webserver.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.ingress.enabled | default true }}
    {{- if eq .Values.ingress.type "gce" }}
    cloud.google.com/backend-config: '{"ports": {"webserver80":"{{ include "lunar-mcpx-webapp.fullname" . }}-webserver"}}'
    {{- end }}
    {{- end }}
spec:
  ports:
    - name: webserver80
      protocol: TCP
      port: 80
      targetPort: 3000
    - name: webserver4000
      protocol: TCP
      port: 4000
      targetPort: 4000
  sessionAffinity: ClientIP
  type: ClusterIP
  selector:
    app: {{ include "lunar-mcpx-webapp.fullname" . }}-webserver
    {{- include "lunar-mcpx-webapp.selectorLabels" . | nindent 4 }}
    {{- with .Values.global.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.webserver.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.webserver.podLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}


{{- if .Values.ingress.enabled | default true }}
{{- if eq .Values.ingress.type "gce" }}
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: {{ include "lunar-mcpx-webapp.fullname" . }}-webserver
spec:
  timeoutSec: 86400
  sessionAffinity:
    affinityType: "GENERATED_COOKIE"
    affinityCookieTtlSec: 86400
  healthCheck:
    checkIntervalSec: 30
    timeoutSec: 10
    healthyThreshold: 1
    unhealthyThreshold: 3
    type: HTTP
    requestPath: /healthcheck
    port: 3000
{{- end }}
{{- end }}

{{- end }}
