apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lunar-mcpx-webapp.fullname" . }}-embedded
type: Opaque
data:
  {{- $xfullname := include "lunar-mcpx-webapp.fullname" . }}
  {{- if .Values.postgres.enabled | default false }}
  DATABASE_URL: {{ printf "postgres://postgres:postgres@%s-postgres:5432/mcpx?schema=public" $xfullname | b64enc | quote }}
  {{- end }}
  {{- if .Values.redis.enabled | default false }}
  REDIS_URL: {{ printf "redis://%s-redis:6379" $xfullname | b64enc | quote }}
  REDIS_USE_CLUSTER: {{ "false" | b64enc | quote }}
  {{- end }}
