{{- if .Values.auth.enabled | default true }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lunar-mcpx-webapp.fullname" . }}-auth
  labels:
    name: {{ include "lunar-mcpx-webapp.fullname" . }}-auth
    app: {{ include "lunar-mcpx-webapp.fullname" . }}-auth
    {{- with .Values.global.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.auth.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.auth.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: {{ include "lunar-mcpx-webapp.fullname" . }}-auth
      {{- include "lunar-mcpx-webapp.selectorLabels" . | nindent 6 }}
      {{- with .Values.global.labels }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.auth.labels }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.auth.podLabels }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
  template:
    metadata:
      labels:
        app: {{ include "lunar-mcpx-webapp.fullname" . }}-auth
        {{- include "lunar-mcpx-webapp.selectorLabels" . | nindent 8 }}
        {{- with .Values.global.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.auth.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.auth.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      initContainers:
        - name: mcpx-auth-prisma-migration
          image: "{{ .Values.auth.image.repository }}:{{ .Values.auth.image.tag | default .Values.global.appVersion | default .Chart.AppVersion }}"
          {{- if or (.Values.global.manageResources.limits) (.Values.global.manageResources.requests) }}
          resources:
            {{- if .Values.global.manageResources.limits }}
            limits:
              {{- with .Values.auth.resources.limits }}
              {{- toYaml . | nindent 14 }}
              {{- end }}
            {{- end }}
            {{- if .Values.global.manageResources.requests }}
            requests:
              {{- with .Values.auth.resources.requests }}
                {{- toYaml . | nindent 14 }}
                {{- end }}
            {{- end }}
          {{- end }}
          command: ["/bin/sh"]
          args: ["-c", "cd /mcpx-webapp && npx prisma migrate deploy;"]
          envFrom:
            - secretRef:
                name: {{ include "lunar-mcpx-webapp.fullname" . }}-embedded
          {{- with .Values.global.extraEnvFromSecrets }}
          {{- range $.Values.global.extraEnvFromSecrets }}
            - secretRef:
                name: {{ . }}
          {{- end }}
          {{- end }}
          {{- with .Values.auth.extraEnvFromSecrets }}
          {{- range $.Values.auth.extraEnvFromSecrets }}
            - secretRef:
                name: {{ . }}
          {{- end }}
          {{- end }}
          env:
            - name: NODE_ENV
              value: "production"
          {{- if .Values.global.extraEnvVars }}
          {{- include "lunar-mcpx-webapp.tplvalues.render" (dict "value" .Values.global.extraEnvVars "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.auth.extraEnvVars }}
          {{- include "lunar-mcpx-webapp.tplvalues.render" (dict "value" .Values.auth.extraEnvVars "context" $) | nindent 12 }}
          {{- end }}

      containers:
        - name: mcpx-auth-container
          image: "{{ .Values.auth.image.repository }}:{{ .Values.auth.image.tag | default .Values.global.appVersion | default .Chart.AppVersion }}"
          ports:
            - containerPort: 8080
          {{- if or (.Values.global.manageResources.limits) (.Values.global.manageResources.requests) }}
          resources:
            {{- if .Values.global.manageResources.limits }}
            limits:
              {{- with .Values.auth.resources.limits }}
              {{- toYaml . | nindent 14 }}
              {{- end }}
            {{- end }}
            {{- if .Values.global.manageResources.requests }}
            requests:
              {{- with .Values.auth.resources.requests }}
                {{- toYaml . | nindent 14 }}
                {{- end }}
            {{- end }}
          {{- end }}
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            runAsUser: 1000
            runAsGroup: 1000
          envFrom:
            - secretRef:
                name: {{ include "lunar-mcpx-webapp.fullname" . }}-embedded
          {{- with .Values.global.extraEnvFromSecrets }}
          {{- range $.Values.global.extraEnvFromSecrets }}
            - secretRef:
                name: {{ . }}
          {{- end }}
          {{- end }}
          {{- with .Values.auth.extraEnvFromSecrets }}
          {{- range $.Values.auth.extraEnvFromSecrets }}
            - secretRef:
                name: {{ . }}
          {{- end }}
          {{- end }}
          env:
            - name: NODE_ENV
              value: "production"
            {{- with .Values.global.caCerts }}
            {{- with .secretName }}
            - name: NODE_EXTRA_CA_CERTS
              value: /usr/local/share/ca-certificates/{{ . }}.crt
            {{- end }}
            {{- end }}
            - name: PORT
              value: "8080"
          {{- if .Values.ingress.enabled }}
            - name: JWT_ISSUER
              value: "https://{{ first .Values.ingress.domains.auth }}"
            - name: CORS_ALLOWED_ORIGINS
              value: "https://{{ first .Values.ingress.domains.admin }},https://{{ first .Values.ingress.domains.ui }},https://{{ first .Values.ingress.domains.router }}"
          {{- end }}
          {{- if .Values.global.extraEnvVars }}
          {{- include "lunar-mcpx-webapp.tplvalues.render" (dict "value" .Values.global.extraEnvVars "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.auth.extraEnvVars }}
          {{- include "lunar-mcpx-webapp.tplvalues.render" (dict "value" .Values.auth.extraEnvVars "context" $) | nindent 12 }}
          {{- end }}

          startupProbe:
            successThreshold: 1
            failureThreshold: 30
            httpGet:
              path: /healthcheck
              port: 8080
              scheme: HTTP
            periodSeconds: 10
          readinessProbe:
            successThreshold: 1
            failureThreshold: 3
            httpGet:
              path: /healthcheck
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 10
          livenessProbe:
            failureThreshold: 10
            httpGet:
              path: /healthcheck
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 30

          {{- with .Values.global.caCerts }}
          volumeMounts:
          {{- with .secretName }}
            - name: {{ . }}
              mountPath: "/usr/local/share/ca-certificates/"
              readOnly: true
          {{- end }}
          {{- end }}
      volumes:
        - name: tmp
          emptyDir: {}
        {{- with .Values.global.caCerts }}
        {{- with .secretName }}
        - name: {{ . }}
          secret:
            secretName: {{ . }}
            items:
              - key: ca.crt
                path: {{ . }}.crt
        {{- end }}
        {{- end }}

      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- range $.Values.global.imagePullSecrets }}
        - name: {{ . }}
        {{- end }}
      {{- end }}
      {{- with .Values.auth.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- end }}
