apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lunar-mcpx-webapp.fullname" . }}-embedded
type: Opaque
data:
  {{- $xfullname := include "lunar-mcpx-webapp.fullname" . }}
  {{- if .Values.postgres.enabled | default false }}
  {{- $postgres_username := .Values.postgres.credentials.username | default "postgres" }}
  {{- $postgres_password := .Values.postgres.credentials.password | default "postgres" }}
  {{- $postgres_database := .Values.postgres.credentials.database | default "mcpx" }}
  DATABASE_URL: {{ printf "postgres://%s:%s@%s-postgres:5432/%s?schema=public" $postgres_username $postgres_password $xfullname $postgres_database | b64enc | quote }}
  {{- end }}
  {{- if .Values.redis.enabled | default false }}
  REDIS_URL: {{ printf "redis://%s-redis.%s.svc.cluster.local:6379" (include "lunar-mcpx-webapp.fullname" .) .Release.Namespace | b64enc | quote }}
  REDIS_IS_CLUSTER: {{ "false" | b64enc | quote }}
  {{- end }}
