{{- if .Values.admin.enabled | default true }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "lunar-mcpx-webapp.fullname" . }}-admin
  labels:
    name: {{ include "lunar-mcpx-webapp.fullname" . }}-admin
    app: {{ include "lunar-mcpx-webapp.fullname" . }}-admin
    {{- with .Values.global.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.admin.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.ingress.enabled | default true }}
    {{- if eq .Values.ingress.type "gce" }}
    cloud.google.com/backend-config: '{"ports": {"admin80":"{{ include "lunar-mcpx-webapp.fullname" . }}-admin"}}'
    {{- end }}
    {{- end }}
spec:
  ports:
    - name: admin80
      protocol: TCP
      port: 80
      targetPort: 8080
  sessionAffinity: ClientIP
  type: ClusterIP
  selector:
    app: {{ include "lunar-mcpx-webapp.fullname" . }}-admin
    {{- include "lunar-mcpx-webapp.selectorLabels" . | nindent 4 }}
    {{- with .Values.global.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.admin.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.admin.podLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}


{{- if .Values.ingress.enabled | default true }}
{{- if eq .Values.ingress.type "gce" }}
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: {{ include "lunar-mcpx-webapp.fullname" . }}-admin
spec:
  timeoutSec: 86400
  sessionAffinity:
    affinityType: "GENERATED_COOKIE"
    affinityCookieTtlSec: 86400
  healthCheck:
    checkIntervalSec: 30
    timeoutSec: 10
    healthyThreshold: 1
    unhealthyThreshold: 3
    type: HTTP
    requestPath: /healthcheck
    port: 8080
{{- end }}
{{- end }}

{{- end }}
