{{- if .Values.ui.enabled | default true }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lunar-mcpx-webapp.fullname" . }}-ui
  labels:
    name: {{ include "lunar-mcpx-webapp.fullname" . }}-ui
    app: {{ include "lunar-mcpx-webapp.fullname" . }}-ui
    {{- with .Values.global.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.ui.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.ui.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: {{ include "lunar-mcpx-webapp.fullname" . }}-ui
      {{- include "lunar-mcpx-webapp.selectorLabels" . | nindent 6 }}
      {{- with .Values.global.labels }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.ui.labels }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.ui.podLabels }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
  template:
    metadata:
      labels:
        app: {{ include "lunar-mcpx-webapp.fullname" . }}-ui
        {{- include "lunar-mcpx-webapp.selectorLabels" . | nindent 8 }}
        {{- with .Values.global.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.ui.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.ui.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: mcpx-ui-container
          image: '{{ .Values.ui.image.repository }}:{{ .Values.ui.image.tag | default (include "lunar-mcpx-webapp.mcpxVersion" .) }}'
          ports:
            - containerPort: 5173
          {{- if or (.Values.global.manageResources.limits) (.Values.global.manageResources.requests) }}
          resources:
            {{- if .Values.global.manageResources.limits }}
            limits:
              {{- with .Values.ui.resources.limits }}
              {{- toYaml . | nindent 14 }}
              {{- end }}
            {{- end }}
            {{- if .Values.global.manageResources.requests }}
            requests:
              {{- with .Values.ui.resources.requests }}
                {{- toYaml . | nindent 14 }}
                {{- end }}
            {{- end }}
          {{- end }}
          envFrom:
            - secretRef:
                name: {{ include "lunar-mcpx-webapp.fullname" . }}-embedded
          {{- with .Values.global.extraEnvFromSecrets }}
          {{- range $.Values.global.extraEnvFromSecrets }}
            - secretRef:
                name: {{ . }}
          {{- end }}
          {{- end }}
          {{- with .Values.ui.extraEnvFromSecrets }}
          {{- range $.Values.ui.extraEnvFromSecrets }}
            - secretRef:
                name: {{ . }}
          {{- end }}
          {{- end }}
          env:
            - name: VITE_ENABLE_ENTERPRISE
              value: "true"
            - name: VITE_MCPX_SERVER_URL
              value: "https://{{ first .Values.ingress.domains.router }}"
          {{- if .Values.global.extraEnvVars }}
          {{- include "lunar-mcpx-webapp.tplvalues.render" (dict "value" .Values.global.extraEnvVars "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.ui.extraEnvVars }}
          {{- include "lunar-mcpx-webapp.tplvalues.render" (dict "value" .Values.ui.extraEnvVars "context" $) | nindent 12 }}
          {{- end }}

          startupProbe:
            successThreshold: 1
            failureThreshold: 30
            httpGet:
              path: /healthcheck
              port: 5173
              scheme: HTTP
            periodSeconds: 10
          readinessProbe:
            successThreshold: 1
            failureThreshold: 3
            httpGet:
              path: /healthcheck
              port: 5173
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 10
          livenessProbe:
            failureThreshold: 10
            httpGet:
              path: /healthcheck
              port: 5173
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 30

      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- range $.Values.global.imagePullSecrets }}
        - name: {{ . }}
        {{- end }}
      {{- end }}
      {{- with .Values.ui.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- end }}
