{{- if .Values.webserver.enabled | default true }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lunar-mcpx-webapp.fullname" . }}-webserver
  labels:
    name: {{ include "lunar-mcpx-webapp.fullname" . }}-webserver
    app: {{ include "lunar-mcpx-webapp.fullname" . }}-webserver
    {{- with .Values.global.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.webserver.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.webserver.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: {{ include "lunar-mcpx-webapp.fullname" . }}-webserver
      {{- include "lunar-mcpx-webapp.selectorLabels" . | nindent 6 }}
      {{- with .Values.global.labels }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.webserver.labels }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.webserver.podLabels }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
  template:
    metadata:
      labels:
        app: {{ include "lunar-mcpx-webapp.fullname" . }}-webserver
        {{- include "lunar-mcpx-webapp.selectorLabels" . | nindent 8 }}
        {{- with .Values.global.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.webserver.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.webserver.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      initContainers:
        - name: mcpx-webserver-prisma-migration
          image: "{{ .Values.webserver.image.repository }}:{{ .Values.webserver.image.tag | default .Values.global.appVersion | default .Chart.AppVersion }}"
          {{- if or (.Values.global.manageResources.limits) (.Values.global.manageResources.requests) }}
          resources:
            {{- if .Values.global.manageResources.limits }}
            limits:
              {{- with .Values.webserver.resources.limits }}
              {{- toYaml . | nindent 14 }}
              {{- end }}
            {{- end }}
            {{- if .Values.global.manageResources.requests }}
            requests:
              {{- with .Values.webserver.resources.requests }}
                {{- toYaml . | nindent 14 }}
                {{- end }}
            {{- end }}
          {{- end }}
          command: ["/bin/sh"]
          args: ["-c", "cd /mcpx-webapp && npx prisma migrate deploy;"]
          envFrom:
            - secretRef:
                name: {{ include "lunar-mcpx-webapp.fullname" . }}-embedded
          {{- with .Values.global.extraEnvFromSecrets }}
          {{- range $.Values.global.extraEnvFromSecrets }}
            - secretRef:
                name: {{ . }}
          {{- end }}
          {{- end }}
          {{- with .Values.webserver.extraEnvFromSecrets }}
          {{- range $.Values.webserver.extraEnvFromSecrets }}
            - secretRef:
                name: {{ . }}
          {{- end }}
          {{- end }}
          env:
            - name: NODE_ENV
              value: "production"
          {{- if .Values.global.extraEnvVars }}
          {{- include "lunar-mcpx-webapp.tplvalues.render" (dict "value" .Values.global.extraEnvVars "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.webserver.extraEnvVars }}
          {{- include "lunar-mcpx-webapp.tplvalues.render" (dict "value" .Values.webserver.extraEnvVars "context" $) | nindent 12 }}
          {{- end }}

      containers:
        - name: mcpx-webserver-container
          image: "{{ .Values.webserver.image.repository }}:{{ .Values.webserver.image.tag | default .Values.global.appVersion | default .Chart.AppVersion }}"
          ports:
            - containerPort: 8080
          {{- if or (.Values.global.manageResources.limits) (.Values.global.manageResources.requests) }}
          resources:
            {{- if .Values.global.manageResources.limits }}
            limits:
              {{- with .Values.webserver.resources.limits }}
              {{- toYaml . | nindent 14 }}
              {{- end }}
            {{- end }}
            {{- if .Values.global.manageResources.requests }}
            requests:
              {{- with .Values.webserver.resources.requests }}
                {{- toYaml . | nindent 14 }}
                {{- end }}
            {{- end }}
          {{- end }}
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            runAsUser: 1000
            runAsGroup: 1000
          envFrom:
            - secretRef:
                name: {{ include "lunar-mcpx-webapp.fullname" . }}-embedded
          {{- with .Values.global.extraEnvFromSecrets }}
          {{- range $.Values.global.extraEnvFromSecrets }}
            - secretRef:
                name: {{ . }}
          {{- end }}
          {{- end }}
          {{- with .Values.webserver.extraEnvFromSecrets }}
          {{- range $.Values.webserver.extraEnvFromSecrets }}
            - secretRef:
                name: {{ . }}
          {{- end }}
          {{- end }}
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "8080"
            - name: HIVE_CONTROLLER_URL
              value: "http://{{ include "lunar-mcpx-webapp.fullname" . }}-controller"
            - name: HIVE_DEFAULT_MCPX_IMAGE_REPO
              value: 'us-central1-docker.pkg.dev/prj-common-442813/mcpx/mcpx-server'
            - name: HIVE_DEFAULT_MCPX_IMAGE_TAG
              value: {{ .Values.ui.image.tag | default (include "lunar-mcpx-webapp.mcpxVersion" .) }}
          {{- if .Values.ingress.enabled }}
            - name: CORS_ALLOWED_ORIGINS
              value: "https://{{ first .Values.ingress.domains.admin }}"
          {{- end }}
          {{- if .Values.global.extraEnvVars }}
          {{- include "lunar-mcpx-webapp.tplvalues.render" (dict "value" .Values.global.extraEnvVars "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.webserver.extraEnvVars }}
          {{- include "lunar-mcpx-webapp.tplvalues.render" (dict "value" .Values.webserver.extraEnvVars "context" $) | nindent 12 }}
          {{- end }}

          startupProbe:
            successThreshold: 1
            failureThreshold: 30
            httpGet:
              path: /healthcheck
              port: 8080
              scheme: HTTP
            periodSeconds: 10
          readinessProbe:
            successThreshold: 1
            failureThreshold: 3
            httpGet:
              path: /healthcheck
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 10
          livenessProbe:
            failureThreshold: 10
            httpGet:
              path: /healthcheck
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 30

      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- range $.Values.global.imagePullSecrets }}
        - name: {{ . }}
        {{- end }}
      {{- end }}
      {{- with .Values.webserver.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- end }}
