{{- if .Values.ui.enabled | default true }}
{{- $tolerations := concat .Values.global.tolerations .Values.ui.tolerations -}}
{{- $repository := include "lunar-mcpx-webapp.mcpxImage" (dict "repo" .Values.ui.image.repository "context" .) -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lunar-mcpx-webapp.fullname" . }}-ui
  labels:
    name: {{ include "lunar-mcpx-webapp.fullname" . }}-ui
    app: {{ include "lunar-mcpx-webapp.fullname" . }}-ui
    {{- with .Values.global.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.ui.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.ui.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: {{ include "lunar-mcpx-webapp.fullname" . }}-ui
      {{- include "lunar-mcpx-webapp.selectorLabels" . | nindent 6 }}
      {{- with .Values.global.labels }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.ui.labels }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.ui.podLabels }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
  template:
    metadata:
      labels:
        app: {{ include "lunar-mcpx-webapp.fullname" . }}-ui
        {{- include "lunar-mcpx-webapp.selectorLabels" . | nindent 8 }}
        {{- with .Values.global.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.ui.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.ui.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      securityContext:
        runAsNonRoot: true
        {{- if not (.Capabilities.APIVersions.Has "security.openshift.io/v1") }}
        runAsUser: 1002
        runAsGroup: 1002
        fsGroup: 1002
        {{- end }}
      initContainers:
        - name: mcpx-ui-prepare-ui-files
          image: '{{ $repository }}:{{ .Values.ui.image.tag | default (include "lunar-mcpx-webapp.mcpxVersion" .) }}'
          command:
            - sh
            - -c
            - |
                if [ ! -f /tmp/lunar/packages/ui/.copied ]; then
                  echo "Copying files /lunar/packages/ui/* -> /tmp/lunar/packages/ui/"
                  cp -r /lunar/packages/ui/* /tmp/lunar/packages/ui/ && touch /tmp/lunar/packages/ui/.copied
                  ls -alh /tmp/lunar/packages/ui/
                else
                  echo 'Files already copied'
                fi
          volumeMounts:
            - name: lunar-packages-ui
              mountPath: /tmp/lunar/packages/ui/
        {{- with concat (.Values.global.extraInitContainers | default (list)) (.Values.ui.extraInitContainers | default (list)) }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      containers:
        - name: mcpx-ui-container
          image: '{{ $repository }}:{{ .Values.ui.image.tag | default (include "lunar-mcpx-webapp.mcpxVersion" .) }}'
          ports:
            - containerPort: 8080
          {{- if or (.Values.global.manageResources.limits) (.Values.global.manageResources.requests) }}
          resources:
            {{- if .Values.global.manageResources.limits }}
            limits:
              {{- with .Values.ui.resources.limits }}
              {{- toYaml . | nindent 14 }}
              {{- end }}
            {{- end }}
            {{- if .Values.global.manageResources.requests }}
            requests:
              {{- with .Values.ui.resources.requests }}
                {{- toYaml . | nindent 14 }}
                {{- end }}
            {{- end }}
          {{- end }}
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            allowPrivilegeEscalation: false
          envFrom:
            - secretRef:
                name: {{ include "lunar-mcpx-webapp.fullname" . }}-embedded
          {{- with .Values.global.extraEnvFromSecrets }}
          {{- range $.Values.global.extraEnvFromSecrets }}
            - secretRef:
                name: {{ . }}
          {{- end }}
          {{- end }}
          {{- with .Values.ui.extraEnvFromSecrets }}
          {{- range $.Values.ui.extraEnvFromSecrets }}
            - secretRef:
                name: {{ . }}
          {{- end }}
          {{- end }}
          env:
            - name: VITE_ENABLE_ENTERPRISE
              value: "true"
            - name: UI_PORT
              value: "8080"
            - name: VITE_MCPX_SERVER_URL
              value: "https://{{ first .Values.ingress.domains.router }}"
            - name: VITE_AUTH_BFF_URL
              value: "https://{{ first .Values.ingress.domains.auth }}"
            - name: VITE_ADMIN_WEBSERVER_URL
              value: "https://{{ first .Values.ingress.domains.webserver }}"
          {{- if .Values.global.extraEnvVars }}
          {{- include "lunar-mcpx-webapp.tplvalues.render" (dict "value" .Values.global.extraEnvVars "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.ui.extraEnvVars }}
          {{- include "lunar-mcpx-webapp.tplvalues.render" (dict "value" .Values.ui.extraEnvVars "context" $) | nindent 12 }}
          {{- end }}

          startupProbe:
            successThreshold: 1
            failureThreshold: 30
            httpGet:
              path: /healthcheck
              port: 8080
              scheme: HTTP
            periodSeconds: 10
          readinessProbe:
            successThreshold: 1
            failureThreshold: 3
            httpGet:
              path: /healthcheck
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 10
          livenessProbe:
            failureThreshold: 10
            httpGet:
              path: /healthcheck
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 30
          volumeMounts:
            - name: lunar-packages-ui
              mountPath: /lunar/packages/ui
        {{- with concat (.Values.global.extraContainers | default (list)) (.Values.ui.extraContainers | default (list)) }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      volumes:
      - name: lunar-packages-ui
        emptyDir: {}
      {{- with mergeOverwrite (deepCopy (.Values.global.affinity | default dict)) (.Values.ui.affinity | default dict) }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with concat (.Values.global.topologySpreadConstraints | default list) (.Values.ui.topologySpreadConstraints | default list) }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- range $.Values.global.imagePullSecrets }}
        - name: {{ . }}
        {{- end }}
      {{- end }}
      {{- with .Values.ui.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with coalesce .Values.ui.priorityClassName .Values.global.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
  {{- end }}
