{{- if .Values.hub.enabled | default true }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "lunar-mcpx-webapp.fullname" . }}-hub
  annotations:
    {{- if .Values.ingress.enabled | default true }}
    {{- if eq .Values.ingress.type "gce" }}
    cloud.google.com/backend-config: '{"ports": {"hub80":"{{ include "lunar-mcpx-webapp.fullname" . }}-hub"}}'
    {{- end }}
    {{- end }}
spec:
  ports:
    - name: hub80
      protocol: TCP
      port: 80
      targetPort: 3000
  sessionAffinity: ClientIP
  type: ClusterIP
  selector:
    app: {{ include "lunar-mcpx-webapp.fullname" . }}-hub
    {{- include "lunar-mcpx-webapp.selectorLabels" . | nindent 4 }}


{{- if .Values.ingress.enabled | default true }}
{{- if eq .Values.ingress.type "gce" }}
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: {{ include "lunar-mcpx-webapp.fullname" . }}-hub
spec:
  timeoutSec: 86400
  sessionAffinity:
    affinityType: "GENERATED_COOKIE"
    affinityCookieTtlSec: 86400
  healthCheck:
    checkIntervalSec: 30
    timeoutSec: 10
    healthyThreshold: 1
    unhealthyThreshold: 3
    type: HTTP
    requestPath: /healthcheck
    port: 3000
{{- end }}
{{- end }}

{{- end }}
