{{- if .Values.admin.enabled | default true }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lunar-mcpx-webapp.fullname" . }}-admin
  labels:
    name: {{ include "lunar-mcpx-webapp.fullname" . }}-admin
    app: {{ include "lunar-mcpx-webapp.fullname" . }}-admin
    {{- with .Values.global.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.admin.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.admin.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: {{ include "lunar-mcpx-webapp.fullname" . }}-admin
      {{- include "lunar-mcpx-webapp.selectorLabels" . | nindent 6 }}
      {{- with .Values.global.labels }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.admin.labels }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.admin.podLabels }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
  template:
    metadata:
      labels:
        app: {{ include "lunar-mcpx-webapp.fullname" . }}-admin
        {{- include "lunar-mcpx-webapp.selectorLabels" . | nindent 8 }}
        {{- with .Values.global.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.admin.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.admin.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: mcpx-admin-container
          image: "{{ .Values.admin.image.repository }}:{{ .Values.admin.image.tag | default .Values.global.appVersion | default .Chart.AppVersion }}"
          ports:
            - containerPort: 3000
          {{- if or (.Values.global.manageResources.limits) (.Values.global.manageResources.requests) }}
          resources:
            {{- if .Values.global.manageResources.limits }}
            limits:
              {{- with .Values.admin.resources.limits }}
              {{- toYaml . | nindent 14 }}
              {{- end }}
            {{- end }}
            {{- if .Values.global.manageResources.requests }}
            requests:
              {{- with .Values.admin.resources.requests }}
                {{- toYaml . | nindent 14 }}
                {{- end }}
            {{- end }}
          {{- end }}
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            runAsUser: 1000
            runAsGroup: 1000
          envFrom:
            - secretRef:
                name: {{ include "lunar-mcpx-webapp.fullname" . }}-embedded
          {{- with .Values.global.extraEnvFromSecrets }}
          {{- range $.Values.global.extraEnvFromSecrets }}
            - secretRef:
                name: {{ . }}
          {{- end }}
          {{- end }}
          {{- with .Values.admin.extraEnvFromSecrets }}
          {{- range $.Values.admin.extraEnvFromSecrets }}
            - secretRef:
                name: {{ . }}
          {{- end }}
          {{- end }}
          env:
            - name: NODE_ENV
              value: "production"
          {{- if .Values.ingress.enabled }}
            - name: API_BASE_URL
              value: "https://{{ first .Values.ingress.domains.webserver }}"
            - name: AUTH_BFF_URL
              value: "https://{{ first .Values.ingress.domains.auth }}"
            - name: MCPX_UI_URL
              value: "https://{{ first .Values.ingress.domains.ui }}"
            - name: DEFAULT_MCPX_TAG
              value: "{{ .Values.ui.image.tag }}"
            - name: DEFAULT_MCPX_REPO
              value: "us-central1-docker.pkg.dev/prj-common-442813/mcpx/mcpx-server"
          {{- end }}
          {{- if .Values.global.extraEnvVars }}
          {{- include "lunar-mcpx-webapp.tplvalues.render" (dict "value" .Values.global.extraEnvVars "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.admin.extraEnvVars }}
          {{- include "lunar-mcpx-webapp.tplvalues.render" (dict "value" .Values.admin.extraEnvVars "context" $) | nindent 12 }}
          {{- end }}

          startupProbe:
            successThreshold: 1
            failureThreshold: 30
            httpGet:
              path: /healthcheck
              port: 3000
              scheme: HTTP
            periodSeconds: 10
          readinessProbe:
            successThreshold: 1
            failureThreshold: 3
            httpGet:
              path: /healthcheck
              port: 3000
              scheme: HTTP
            periodSeconds: 10
            timeoutSeconds: 10
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthcheck
              port: 3000
              scheme: HTTP
            periodSeconds: 10
            timeoutSeconds: 10

      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- range $.Values.global.imagePullSecrets }}
        - name: {{ . }}
        {{- end }}
      {{- end }}
      {{- with .Values.admin.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- end }}
