---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "lunar-mcpx-webapp.fullname" . }}-db-ses-rtn
  labels:
    service: {{ include "lunar-mcpx-webapp.fullname" . }}-db-ses-rtn
    {{- with .Values.global.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.jobs.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  schedule: "0 */4 * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 3 # Retries 3 times before marking the job as failed
      activeDeadlineSeconds: 3600 # The job will be terminated after 1 hour
      template:
        metadata:
          labels:
            service: {{ include "lunar-mcpx-webapp.fullname" . }}-db-ses-rtn
            {{- include "lunar-mcpx-webapp.selectorLabels" . | nindent 12 }}
            {{- with .Values.global.labels }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- with .Values.jobs.labels }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- with .Values.jobs.podLabels }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
        spec:
          restartPolicy: OnFailure
          containers:
            - name: job-runner
              image: "{{ .Values.jobs.image.repository }}:{{ .Values.jobs.image.tag | default .Values.global.appVersion | default .Chart.AppVersion }}"
              args:
                - clean-terminated-sessions
              {{- if or (.Values.global.manageResources.limits) (.Values.global.manageResources.requests) }}
              resources:
                {{- if .Values.global.manageResources.limits }}
                limits:
                  {{- with .Values.jobs.resources.limits }}
                  {{- toYaml . | nindent 18 }}
                  {{- end }}
                {{- end }}
                {{- if .Values.global.manageResources.requests }}
                requests:
                  {{- with .Values.jobs.resources.requests }}
                    {{- toYaml . | nindent 18 }}
                    {{- end }}
                {{- end }}
              {{- end }}
              envFrom:
                - secretRef:
                    name: {{ include "lunar-mcpx-webapp.fullname" . }}-embedded
              {{- with .Values.global.extraEnvFromSecrets }}
              {{- range $.Values.global.extraEnvFromSecrets }}
                - secretRef:
                    name: {{ . }}
              {{- end }}
              {{- end }}
              {{- with .Values.jobs.extraEnvFromSecrets }}
              {{- range $.Values.jobs.extraEnvFromSecrets }}
                - secretRef:
                    name: {{ . }}
              {{- end }}
              {{- end }}
              env:
              {{- if .Values.global.extraEnvVars }}
              {{- include "lunar-mcpx-webapp.tplvalues.render" (dict "value" .Values.global.extraEnvVars "context" $) | nindent 16 }}
              {{- end }}
              {{- if .Values.jobs.extraEnvVars }}
              {{- include "lunar-mcpx-webapp.tplvalues.render" (dict "value" .Values.jobs.extraEnvVars "context" $) | nindent 16 }}
              {{- end }}

          {{- with .Values.global.imagePullSecrets }}
          imagePullSecrets:
            {{- range $.Values.global.imagePullSecrets }}
            - name: {{ . }}
            {{- end }}
          {{- end }}
          {{- with .Values.jobs.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}

{{- if .Values.hibernation.cronSchedule }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "lunar-mcpx-webapp.fullname" . }}-hibernate-instances
  labels:
    service: {{ include "lunar-mcpx-webapp.fullname" . }}-hibernate-instances
    {{- with .Values.global.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.jobs.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  schedule: {{ .Values.hibernation.cronSchedule | quote }}
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 3 # Retries 3 times before marking the job as failed
      activeDeadlineSeconds: 3600 # The job will be terminated after 1 hour
      template:
        metadata:
          labels:
            service: {{ include "lunar-mcpx-webapp.fullname" . }}-hibernate-instances
            {{- include "lunar-mcpx-webapp.selectorLabels" . | nindent 12 }}
            {{- with .Values.global.labels }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- with .Values.jobs.labels }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- with .Values.jobs.podLabels }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
        spec:
          restartPolicy: OnFailure
          containers:
            - name: job-runner
              image: "{{ .Values.jobs.image.repository }}:{{ .Values.jobs.image.tag | default .Values.global.appVersion | default .Chart.AppVersion }}"
              args:
                - hibernate-instances
              {{- if or (.Values.global.manageResources.limits) (.Values.global.manageResources.requests) }}
              resources:
                {{- if .Values.global.manageResources.limits }}
                limits:
                  {{- with .Values.jobs.resources.limits }}
                  {{- toYaml . | nindent 18 }}
                  {{- end }}
                {{- end }}
                {{- if .Values.global.manageResources.requests }}
                requests:
                  {{- with .Values.jobs.resources.requests }}
                    {{- toYaml . | nindent 18 }}
                    {{- end }}
                {{- end }}
              {{- end }}
              envFrom:
                - secretRef:
                    name: {{ include "lunar-mcpx-webapp.fullname" . }}-embedded
              {{- with .Values.global.extraEnvFromSecrets }}
              {{- range $.Values.global.extraEnvFromSecrets }}
                - secretRef:
                    name: {{ . }}
              {{- end }}
              {{- end }}
              {{- with .Values.jobs.extraEnvFromSecrets }}
              {{- range $.Values.jobs.extraEnvFromSecrets }}
                - secretRef:
                    name: {{ . }}
              {{- end }}
              {{- end }}
              env:
                - name: HIVE_CONTROLLER_URL
                  value: "http://{{ include "lunar-mcpx-webapp.fullname" . }}-controller"
              {{- if .Values.global.extraEnvVars }}
              {{- include "lunar-mcpx-webapp.tplvalues.render" (dict "value" .Values.global.extraEnvVars "context" $) | nindent 16 }}
              {{- end }}
              {{- if .Values.jobs.extraEnvVars }}
              {{- include "lunar-mcpx-webapp.tplvalues.render" (dict "value" .Values.jobs.extraEnvVars "context" $) | nindent 16 }}
              {{- end }}

          {{- with .Values.global.imagePullSecrets }}
          imagePullSecrets:
            {{- range $.Values.global.imagePullSecrets }}
            - name: {{ . }}
            {{- end }}
          {{- end }}
          {{- with .Values.jobs.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
{{- end }}
