{{- if .Values.hub.enabled | default true }}
{{- $tolerations := concat .Values.global.tolerations .Values.hub.tolerations -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lunar-mcpx-webapp.fullname" . }}-hub
  labels:
    name: {{ include "lunar-mcpx-webapp.fullname" . }}-hub
    app: {{ include "lunar-mcpx-webapp.fullname" . }}-hub
    {{- with .Values.global.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.hub.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.hub.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: {{ include "lunar-mcpx-webapp.fullname" . }}-hub
      {{- include "lunar-mcpx-webapp.selectorLabels" . | nindent 6 }}
      {{- with .Values.global.labels }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.hub.labels }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.hub.podLabels }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
  template:
    metadata:
      labels:
        app: {{ include "lunar-mcpx-webapp.fullname" . }}-hub
        {{- include "lunar-mcpx-webapp.selectorLabels" . | nindent 8 }}
        {{- with .Values.global.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.hub.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.hub.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      initContainers:
        - name: mcpx-hub-prisma-migration
          image: "{{ .Values.hub.image.repository }}:{{ .Values.hub.image.tag | default .Values.global.appVersion | default .Chart.AppVersion }}"
          {{- if or (.Values.global.manageResources.limits) (.Values.global.manageResources.requests) }}
          resources:
            {{- if .Values.global.manageResources.limits }}
            limits:
              {{- with .Values.hub.resources.limits }}
              {{- toYaml . | nindent 14 }}
              {{- end }}
            {{- end }}
            {{- if .Values.global.manageResources.requests }}
            requests:
              {{- with .Values.hub.resources.requests }}
                {{- toYaml . | nindent 14 }}
                {{- end }}
            {{- end }}
          {{- end }}
          command: ["/bin/sh"]
          args: ["-c", "cd /mcpx-webapp && npx prisma migrate deploy"]
          envFrom:
            - secretRef:
                name: {{ include "lunar-mcpx-webapp.fullname" . }}-embedded
          {{- with .Values.global.extraEnvFromSecrets }}
          {{- range $.Values.global.extraEnvFromSecrets }}
            - secretRef:
                name: {{ . }}
          {{- end }}
          {{- end }}
          {{- with .Values.hub.extraEnvFromSecrets }}
          {{- range $.Values.hub.extraEnvFromSecrets }}
            - secretRef:
                name: {{ . }}
          {{- end }}
          {{- end }}
          env:
            - name: NODE_ENV
              value: "production"
          {{- if .Values.global.extraEnvVars }}
          {{- include "lunar-mcpx-webapp.tplvalues.render" (dict "value" .Values.global.extraEnvVars "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.hub.extraEnvVars }}
          {{- include "lunar-mcpx-webapp.tplvalues.render" (dict "value" .Values.hub.extraEnvVars "context" $) | nindent 12 }}
          {{- end }}

      containers:
        - name: mcpx-hub-container
          image: "{{ .Values.hub.image.repository }}:{{ .Values.hub.image.tag | default .Values.global.appVersion | default .Chart.AppVersion }}"
          ports:
            - containerPort: 8080
          {{- if or (.Values.global.manageResources.limits) (.Values.global.manageResources.requests) }}
          resources:
            {{- if .Values.global.manageResources.limits }}
            limits:
              {{- with .Values.hub.resources.limits }}
              {{- toYaml . | nindent 14 }}
              {{- end }}
            {{- end }}
            {{- if .Values.global.manageResources.requests }}
            requests:
              {{- with .Values.hub.resources.requests }}
                {{- toYaml . | nindent 14 }}
                {{- end }}
            {{- end }}
          {{- end }}
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            runAsUser: 1000
            runAsGroup: 1000
          envFrom:
            - secretRef:
                name: {{ include "lunar-mcpx-webapp.fullname" . }}-embedded
          {{- with .Values.global.extraEnvFromSecrets }}
          {{- range $.Values.global.extraEnvFromSecrets }}
            - secretRef:
                name: {{ . }}
          {{- end }}
          {{- end }}
          {{- with .Values.hub.extraEnvFromSecrets }}
          {{- range $.Values.hub.extraEnvFromSecrets }}
            - secretRef:
                name: {{ . }}
          {{- end }}
          {{- end }}
          env:
            - name: NODE_ENV
              value: "production"
            {{- with .Values.global.caCerts }}
            {{- with .secretName }}
            - name: NODE_EXTRA_CA_CERTS
              value: /usr/local/share/ca-certificates/{{ . }}.crt
            {{- end }}
            {{- end }}
            - name: PORT
              value: "8080"
            - name: HIVE_CONTROLLER_URL
              value: "http://{{ include "lunar-mcpx-webapp.fullname" . }}-controller"
          {{- if .Values.global.extraEnvVars }}
          {{- include "lunar-mcpx-webapp.tplvalues.render" (dict "value" .Values.global.extraEnvVars "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.hub.extraEnvVars }}
          {{- include "lunar-mcpx-webapp.tplvalues.render" (dict "value" .Values.hub.extraEnvVars "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.hub.staticOauth | default dict | keys }}
            - name: MCPX_STATIC_OAUTH_CONFIG
              value: {{ .Values.hub.staticOauth | toJson | quote }}
          {{- end }}

          startupProbe:
            successThreshold: 1
            failureThreshold: 30
            httpGet:
              path: /healthcheck
              port: 8080
              scheme: HTTP
            periodSeconds: 10
          readinessProbe:
            successThreshold: 1
            failureThreshold: 3
            httpGet:
              path: /healthcheck
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 10
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthcheck
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 10

          {{- with .Values.global.caCerts }}
          volumeMounts:
          {{- with .secretName }}
            - name: {{ . }}
              mountPath: "/usr/local/share/ca-certificates/"
              readOnly: true
          {{- end }}
          {{- end }}
      volumes:
        - name: tmp
          emptyDir: {}
        {{- with .Values.global.caCerts }}
        {{- with .secretName }}
        - name: {{ . }}
          secret:
            secretName: {{ . }}
            items:
              - key: ca.crt
                path: {{ . }}.crt
        {{- end }}
        {{- end }}

      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- range $.Values.global.imagePullSecrets }}
        - name: {{ . }}
        {{- end }}
      {{- end }}
      {{- with .Values.hub.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- end }}
