{{- if .Values.router.enabled | default true }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "lunar-mcpx-webapp.fullname" . }}-router
  labels:
    name: {{ include "lunar-mcpx-webapp.fullname" . }}-router
    app: {{ include "lunar-mcpx-webapp.fullname" . }}-router
    {{- with .Values.global.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.router.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.ingress.enabled | default true }}
    {{- if eq .Values.ingress.type "gce" }}
    cloud.google.com/backend-config: '{"ports": {
      "router80": "{{ include "lunar-mcpx-webapp.fullname" . }}-router",
      "ui8080": "{{ include "lunar-mcpx-webapp.fullname" . }}-router"
    }}'
    {{- end }}
    {{- end }}
spec:
  ports:
    - name: router80
      port: 80
      targetPort: 9000
    - name: ui8080
      port: 8080
      targetPort: 8080
  sessionAffinity: ClientIP
  type: ClusterIP
  selector:
    app: {{ include "lunar-mcpx-webapp.fullname" . }}-router
    {{- include "lunar-mcpx-webapp.selectorLabels" . | nindent 4 }}
    {{- with .Values.global.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.router.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.router.podLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}


{{- if .Values.ingress.enabled | default true }}
{{- if eq .Values.ingress.type "gce" }}
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: {{ include "lunar-mcpx-webapp.fullname" . }}-router
spec:
  timeoutSec: 3600
  connectionDraining:
    drainingTimeoutSec: 60
  sessionAffinity:
    affinityType: "CLIENT_IP"
    affinityCookieTtlSec: 3600
  healthCheck:
    checkIntervalSec: 10
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 3
    type: HTTP
    requestPath: /healthcheck
    port: 8080
{{- end }}
{{- end }}

{{- end }}