{{- if .Values.postgres.enabled | default false }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lunar-mcpx-webapp.fullname" . }}-postgres-env
type: Opaque
data:
  POSTGRES_USER: {{ "postgres" | b64enc | quote }}
  POSTGRES_PASSWORD: {{ "postgres" | b64enc | quote }}
  POSTGRES_DB: {{ "mcpx" | b64enc | quote }}
{{- end }}
