{{- if .Values.postgres.enabled | default false }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lunar-mcpx-webapp.fullname" . }}-postgres-env
type: Opaque
data:
  POSTGRES_USER: {{ .Values.postgres.credentials.username | default "postgres" | b64enc | quote }}
  POSTGRES_PASSWORD: {{  .Values.postgres.credentials.password | default "postgres" | b64enc | quote }}
  POSTGRES_DB: {{  .Values.postgres.credentials.database | default "mcpx" | b64enc | quote }}
{{- end }}
