{{- if .Values.redis.enabled | default false }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "lunar-mcpx-webapp.fullname" . }}-redis
  labels:
    name: {{ include "lunar-mcpx-webapp.fullname" . }}-redis
    app: {{ include "lunar-mcpx-webapp.fullname" . }}-redis
spec:
  selector:
    matchLabels:
      app: {{ include "lunar-mcpx-webapp.fullname" . }}-redis
      {{- include "lunar-mcpx-webapp.selectorLabels" . | nindent 6 }}
  serviceName: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ include "lunar-mcpx-webapp.fullname" . }}-redis
        {{- include "lunar-mcpx-webapp.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: db
          image: redis:8.2-alpine
          command: []
          args:
            - redis-server
            - /etc/redis/redis.conf
          resources:
            requests:
              memory: "1024Mi"
              cpu: "256m"
            limits:
              memory: "1024Mi"
              cpu: "256m"
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: conf
              mountPath: /etc/redis/
              readOnly: false
            {{- if .Values.redis.persistence.enabled | default false }}
            - name: data
              mountPath: /data
            {{- end }}
          livenessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 5
      securityContext:
        fsGroup: 1000
      volumes:
        - name: conf
          configMap:
            name: {{ include "lunar-mcpx-webapp.fullname" . }}-redis-config
            defaultMode: 0644
  {{- if .Values.redis.persistence.enabled | default false }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        {{- if .Values.redis.persistence.accessModes }}
        accessModes: {{ .Values.redis.persistence.accessModes }}
        {{- else }}
        accessModes: [ "ReadWriteOnce" ]
        {{- end }}
        {{- if .Values.redis.persistence.storageClassName }}
        storageClassName: {{ .Values.redis.persistence.storageClassName }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.redis.persistence.size | default "5Gi" }}
  {{- end }}

{{- end }}
