name: Helm Chart Release
on:
  workflow_dispatch:
    inputs:
      chart-name:
        description: "Chart name to release (e.g., lunar-proxy or lunar-mcpx)"
        required: true
        type: choice
        options:
          - lunar-proxy
          - lunar-mcpx
      version: # Effectively, the version of Lunar Gateway's Docker image tag
        description: "Version to deploy"
        required: true
        type: string
      chart-version: # Effectively, the version of the Helm chart. Overrides can be made for fixes in the chart with the suffix `-fix<number>`
        description: "Chart version to package (optional, defaults to 'version')"
        required: false
        type: string

jobs:
  helm-chart:
    permissions:
      contents: write
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config user.name "DevOps"
          git config user.email "devops@lunar.dev"

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Filter out pre-release versions
        run: |
          if [[ "${{ inputs.version }}" == *-* ]]; then
          echo "Suffix detected in version: ${{ inputs.version }}."
            if [[ ! "${{ inputs.version }}" =~ ^[0-9]+\.[0-9]+\.[0-9]+-fix[0-9]*$ ]]; then
              echo "Filtering out chart version: ${{ inputs.version }}."
              exit 0
            else
              echo "Fix version detected: ${{ inputs.version }}."
            fi
          else
            echo "Stable version detected: ${{ inputs.version }}."
          fi

      - name: Set Chart Version
        id: set-chart-version
        run: |
          if [ -z "${{ inputs.chart-version }}" ]; then
            echo "Using version input as chart-version."
            echo "chart_version=${{ inputs.version }}" >> $GITHUB_ENV
          else
            echo "Using provided chart-version input."
            echo "chart_version=${{ inputs.chart-version }}" >> $GITHUB_ENV
          fi

      # Render the README from the template using envsubst
      - name: Render README from template
        run: |
          # Ensure the environment variable is exported so that envsubst can pick it up
          export CHART_VERSION="${{ env.chart_version }}"
          envsubst < charts/${{ inputs.chart-name }}/README.tpl.md > charts/${{ inputs.chart-name }}/README.md

      # Commit the updated README.md if there are any changes
      - name: Commit updated README
        run: |
          git add charts/${{ inputs.chart-name }}/README.md
          if ! git diff --cached --quiet; then
            git commit -m "Update ${{ inputs.chart-name }} README with chart version v${{ env.chart_version }}"
            git push
          else
            echo "No changes in charts/${{ inputs.chart-name }}/README.md to commit."
          fi

      - name: Package
        run: |
          rm -rf .cr-release-packages
          mkdir -p .cr-release-packages
          helm package "charts/${{ inputs.chart-name }}" --version v${{ env.chart_version }} --app-version v${{ inputs.version }} --destination=.cr-release-packages

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        with:
          skip_packaging: true
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
