name: Helm Chart Release
on:
    workflow_dispatch:
        inputs:
          version:
            description: "Version to deploy"
            required: false
            default: "latest"
            type: string

jobs:
  helm-chart:
    permissions:
      contents: write
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config user.name "DevOps"
          git config user.email "devops@lunar.dev"

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Package
        run: |
          rm -rf .cr-release-packages
          mkdir -p .cr-release-packages
          helm package "charts/lunar-proxy" --version v${{ inputs.version }} --app-version v${{ inputs.version }} --destination=.cr-release-packages

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        with:
          skip_packaging: true
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
