{{- if not .Values.lunarStreamsEnabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: policies.yaml
  namespace: {{ default .Release.Namespace }}
  labels:
    app: "{{ include "lunar-proxy.fullname" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
data:
  policies.yaml: |
    {{- if .Files.Get "policies.yaml" }}
      {{ .Files.Get "policies.yaml" | nindent 4 }}
    {{- else }}
      ---
      {{ toYaml .Values.policies | nindent 4 }}
    {{- end }}

immutable: false
{{- end -}}
{{- if .Values.lunarStreamsEnabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: flows
  namespace: {{ default .Release.Namespace }}
  labels:
    app: "{{ include "lunar-proxy.fullname" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
data:
  {{- $flowsPath := .Values.flowsPath }}
  {{- $yamlFiles := .Files.Glob (printf "%s/*.yaml" $flowsPath) }}
  {{- $ymlFiles := .Files.Glob (printf "%s/*.yml" $flowsPath) }}
  {{- $files := append $yamlFiles $ymlFiles }}

  {{- if $files }}
    {{- range $file := $files }}
    {{ base $file.Path }}: |
      {{ .Files.Get $file.Path | nindent 4 }}
    {{- end }}
  {{- else }}
    # Fallback to the original values.yaml-based values if no .yaml/.yml files found
    {{- range $key, $value := .Values.flows }}
      {{ $key }}: |
        {{ $value | nindent 4 }}
    {{- end }}
  {{- end }}


immutable: false
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: quotas
  namespace: {{ default .Release.Namespace }}
  labels:
    app: "{{ include "lunar-proxy.fullname" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
data:
  {{- $flowsPath := .Values.flowsPath }}
  {{- $yamlFiles := .Files.Glob (printf "%s/*.yaml" $flowsPath) }}
  {{- $ymlFiles := .Files.Glob (printf "%s/*.yml" $flowsPath) }}
  {{- $files := append $yamlFiles $ymlFiles }}

  {{- if $files }}
    {{- range $file := $files }}
    {{ base $file.Path }}: |
      {{ .Files.Get $file.Path | nindent 4 }}
    {{- end }}
  {{- else }}
    # Fallback to the original values.yaml-based values if no .yaml/.yml files found
    {{- range $key, $value := .Values.quotas }}
      {{ $key }}: |
        {{ $value | nindent 4 }}
    {{- end }}    
  {{- end }}
immutable: false
{{- end -}}
