# Policies support
{{- if not .Values.lunarStreamsEnabled }}
{{- if .Values.configMapNames.policies }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: lunar-gateway-policies
  namespace: {{ default .Release.Namespace }}
  labels:
    app: "{{ include "lunar-proxy.fullname" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
data:
  policies.yaml: |

    ---
    {{- toYaml .Values.configFiles.policies | nindent 4 }}
immutable: false
{{- end }}
{{- end -}}

# Flows support start
{{- if .Values.lunarStreamsEnabled }}
{{- if not .Values.configMapNames.flows }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: lunar-gateway-flows
  namespace: {{ default .Release.Namespace }}
  labels:
    app: "{{ include "lunar-proxy.fullname" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
data:
{{- range $key, $value := .Values.configFiles.flows }}
  {{ $key }}: |
    {{ $value | nindent 4 }}
{{- end }}
immutable: false
{{- end }}

{{- if not .Values.configMapNames.quotas }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: lunar-gateway-quotas
  namespace: {{ default .Release.Namespace }}
  labels:
    app: "{{ include "lunar-proxy.fullname" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
data:
  # No need to define data here; it will be provided via the external ConfigMap
{{- range $key, $value := .Values.configFiles.quotas }}
  {{ $key }}: |
    {{ $value | nindent 4 }}
{{- end }}
immutable: false
{{- end }}

{{- if not .Values.configMapNames.pathParams }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: lunar-gateway-path-params
  namespace: {{ default .Release.Namespace }}
  labels:
    app: "{{ include "lunar-proxy.fullname" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
data:
{{- range $key, $value := .Values.configFiles.pathParams }}
  {{ $key }}: |
    {{ $value | nindent 4 }}
{{- end }}
immutable: false
{{- end }}

{{- if not .Values.configMapNames.root }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: lunar-gateway-root
  namespace: {{ default .Release.Namespace }}
  labels:
    app: "{{ include "lunar-proxy.fullname" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
data:
{{- range $key, $value := .Values.configFiles.root }}
  {{ $key }}: |
    {{ $value | nindent 4 }}
{{- end }}
immutable: false
{{- end }} 

# Flows support end
{{- end }} 
