{{- if not .Values.lunarStreamsEnabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: policies.yaml
  namespace: {{ default .Release.Namespace }}
  labels:
    app: "{{ include "lunar-proxy.fullname" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
data:
  {{- if .Values.configMapNames.policies }}
  # No need to define data here; it will be provided via the external ConfigMap
  {{- else }}
  policies.yaml: |

    ---
    {{- toYaml .Values.policies | nindent 4 }}
  {{- end}}
immutable: false
{{- end -}}
{{- if .Values.lunarStreamsEnabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: flows
  namespace: {{ default .Release.Namespace }}
  labels:
    app: "{{ include "lunar-proxy.fullname" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
data:
{{- if .Values.configMapNames.flows }}
  # No need to define data here; it will be provided via the external ConfigMap
{{- else }}
{{- range $key, $value := .Values.flows }}
  {{ $key }}: |
    {{ $value | nindent 4 }}
{{- end }}
{{- end }}
immutable: false
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: quotas
  namespace: {{ default .Release.Namespace }}
  labels:
    app: "{{ include "lunar-proxy.fullname" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
data:
{{- if .Values.configMapNames.quotas }}
  # No need to define data here; it will be provided via the external ConfigMap
{{- else }}
{{- range $key, $value := .Values.quotas }}
  {{ $key }}: |
    {{ $value | nindent 4 }}
{{- end }}
{{- end }}
immutable: false
{{- end }}
