---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lunar-proxy.fullname" . }}
  namespace: {{ default .Release.Namespace }}
  labels:
    {{- include "lunar-proxy.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "lunar-proxy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if .Values.metrics.datadog.enabled }}
        ad.datadoghq.com/lunar-proxy.checks: |
          {
            "openmetrics": {
              "init_config": {},
              "instances": [
                {
                  "openmetrics_endpoint": "http://%%host%%:{{ .Values.serviceMonitor.port }}/metrics",
                  "namespace": "{{ .Values.metrics.datadog.namespace }}",
                  "metrics": {{ toJson .Values.metrics.datadog.includedMetrics }}
                }
              ]
            }
          }
        {{- end }}
      labels:
        {{- include "lunar-proxy.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "lunar-proxy.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: '{{ include "image.repository" . | trim }}:{{ .Values.image.tag | default .Chart.AppVersion }}'
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            httpGet:
              path: {{include "lunar-proxy.healthcheck.path" .}}
              port: {{include "lunar-proxy.healthcheck.port" .}}
          readinessProbe:
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            httpGet:
              path: {{include "lunar-proxy.healthcheck.path" .}}
              port: {{include "lunar-proxy.healthcheck.port" .}}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: LOG_LEVEL
              value: {{ .Values.logLevel }}
            - name: BIND_PORT
              value: {{ toString .Values.service.port | quote }}
            - name: LUNAR_FLUSH_SECONDS
              value: {{ toString .Values.lunarFlushSeconds | quote }}
            - name: LUNAR_TELEMETRY
              value: {{ toString .Values.telemetryEnabled | quote }}
          {{- if .Values.env }}
            - name: ENV
              value: {{ .Values.env }}
          {{- end }}
          {{- if .Values.tenantName }}
            - name: TENANT_NAME
              value: {{ .Values.tenantName }}
          {{- end }}
          {{- if .Values.awsAccessKeyId }}
            - name: AWS_ACCESS_KEY_ID
              value: {{ .Values.awsAccessKeyId }}
          {{- end }}
          {{- if .Values.awsSecretAccessKey }}
            - name: AWS_SECRET_ACCESS_KEY
              value: {{ .Values.awsSecretAccessKey }}
          {{- end }}
          {{- if .Values.lunarManaged }}
            - name: LUNAR_MANAGED
              value: {{ .Values.lunarManaged }}
          {{- end }}
          {{- if .Values.lunarHubURL }}
            - name: LUNAR_HUB_URL
              value: {{ .Values.lunarHubURL }}
          {{- end }}
          {{- if .Values.lunarAPIKey }}
            - name: LUNAR_API_KEY
              value: {{ .Values.lunarAPIKey }}
          {{- else if .Values.lunarAPIKeySecretName }}
            - name: LUNAR_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.lunarAPIKeySecretName }}
                  key: lunarAPIKey
          {{- end }}
          {{- if .Values.lunarStreamsEnabled }}
            - name: LUNAR_STREAMS_ENABLED
              value: {{ toString .Values.lunarStreamsEnabled | quote }}
          {{- end }}

          {{- if .Values.telemetryLogLevel }}
              - name: LUNAR_TELEMETRY_LOG_LEVEL
              value: {{ .Values.telemetryLogLevel }}
          {{- end}}          

          # Timeouts
          {{- if .Values.timeouts.spoe.processingTimeoutSec }}
            - name: LUNAR_SPOE_PROCESSING_TIMEOUT_SEC
              value: {{ toString .Values.timeouts.spoe.processingTimeoutSec | quote }}
          {{- end }}
          {{- if .Values.timeouts.spoe.helloTimeoutMillis }}
            - name: LUNAR_SPOE_HELLO_TIMEOUT_MS
              value: {{ toString .Values.timeouts.spoe.helloTimeoutMillis | quote }}
          {{- end }}

          {{- if .Values.timeouts.proxy.connectTimeoutSec }}
            - name: LUNAR_CONNECT_TIMEOUT_SEC
              value: {{ toString .Values.timeouts.proxy.connectTimeoutSec | quote }}
          {{- end }}
          {{- if .Values.timeouts.proxy.clientTimeoutSec }}
            - name: LUNAR_CLIENT_TIMEOUT_SEC
              value: {{ toString .Values.timeouts.proxy.clientTimeoutSec | quote }}
          {{- end }}
          {{- if .Values.timeouts.proxy.serverTimeoutSec }}
            - name: LUNAR_SERVER_TIMEOUT_SEC
              value: {{ toString .Values.timeouts.proxy.serverTimeoutSec | quote }}
          {{- end }}
          {{- if .Values.timeouts.retryRequestTimeoutSec }}
            - name: LUNAR_RETRY_REQUEST_TIMEOUT_SEC
              value: {{ toString .Values.timeouts.retryRequestTimeoutSec | quote }}
          {{- end }}
          # Lunar Cluster
          {{- if .Values.lunarCluster.staleThresholdPeriodInSec }}
            - name: LUNAR_CLUSTER_STALE_THRESHOLD_PERIOD_IN_SEC
              value: {{ toString .Values.lunarCluster.staleThresholdPeriodInSec | quote }}
          {{- end }}
          {{- if .Values.lunarCluster.livenessUpdatedPeriodInSec }}
            - name: LUNAR_CLUSTER_LIVENESS_UPDATED_PERIOD_IN_SEC
              value: {{ toString .Values.lunarCluster.livenessUpdatedPeriodInSec | quote }}
          {{- end }}
          # Redis
          {{- if .Values.redis.url }}
            - name: REDIS_URL
              value: {{ .Values.redis.url }}
          {{- end }}
          {{- if .Values.redis.useCluster }}
            - name: REDIS_USE_CLUSTER
              value: {{ toString .Values.redis.useCluster | quote }}
          {{- end }}          
          {{- if .Values.redis.prefix }}
            - name: REDIS_PREFIX
              value: {{ .Values.redis.prefix }}
          {{- end }}                    
          
          {{- if .Values.redis.useCaCert }}
            - name: REDIS_USE_CA_CERT
              value: {{ toString .Values.redis.useCaCert | quote }}
          {{- end }}              
          {{- if .Values.redis.caCertPath }}
            - name: REDIS_CA_CERT_PATH
              value: {{ .Values.redis.caCertPath }}
          {{- end }}              
          {{- if .Values.redis.useClientCert }}
            - name: REDIS_USE_CLIENT_CERT
              value: {{ toString .Values.redis.useClientCert | quote }}
          {{- end }}
          {{- if .Values.redis.clientCertPath }}
            - name: REDIS_CLIENT_CERT_PATH
              value: {{ .Values.redis.clientCertPath }}
          {{- end }}              
          {{- if .Values.redis.clientKeyPath }}
            - name: REDIS_CLIENT_KEY_PATH
              value: {{ .Values.redis.clientKeyPath }}
          {{- end }}

          # Gateway 
          {{- if .Values.gateway.maxConn }}
            - name: LUNAR_MAXCONN
              value: {{ toString .Values.gateway.maxConn | quote }}
          {{- end }}
          {{- if .Values.gateway.bufferSize }}
            - name: GATEWAY_BUFFER_SIZE
              value: {{ toString .Values.gateway.bufferSize | quote }}
          {{- end }}
          {{- if .Values.gateway.accessLogOutput }}
            - name: LUNAR_ACCESS_LOGS_OUTPUT
              value: {{ .Values.gateway.accessLogOutput }}
          {{- end }}
          {{- if .Values.gateway.doctorReportIntervalMinutes }}
            - name: DOCTOR_REPORT_INTERVAL_MINUTES
              value: {{ toString .Values.gateway.doctorReportIntervalMinutes | quote }}
          {{- end }}

          {{- if .Values.tlsPassthrough }}
            - name: TLS_PASSTHROUGH_ON
              value: {{ toString .Values.tlsPassthrough | quote }}
          {{- end }}                                        


          volumeMounts:
          {{- if .Values.lunarStreamsEnabled }}
            - mountPath: /etc/lunar-proxy
              name: root
            - mountPath: /etc/lunar-proxy/flows
              name: flows
            - mountPath: /etc/lunar-proxy/quotas
              name: quotas
            - mountPath: /etc/lunar-proxy/path_params
              name: path-params
            {{- if .Values.secretNames.tlsCerts }}
            - mountPath: /etc/lunar-proxy/certs/tls
              name: tls-certs
            {{- end }}
            {{- if .Values.secretNames.mtlsCerts }}
            - mountPath: /etc/lunar-proxy/certs/mtls
              name: mtls-certs
            {{- end }}            
          {{- else }}
            - mountPath: /etc/lunar-proxy
              name: policies
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      {{- if .Values.lunarStreamsEnabled }}
      {{- if .Values.configMapNames.flows }}
        - configMap:
            name: {{ .Values.configMapNames.flows }}
          name: flows      
      {{- else }}
        - configMap:
            name: lunar-gateway-flows
          name: flows
      {{- end }}
      {{- if .Values.configMapNames.quotas }}
        - configMap:
            name: {{ .Values.configMapNames.quotas }}
          name: quotas      
      {{- else }}
        - configMap:
            name: lunar-gateway-quotas
          name: quotas
      {{- end }}

      {{- if .Values.configMapNames.pathParams }}
        - configMap:
            name: {{ .Values.configMapNames.pathParams }}
          name: path-params
      {{- else }}
        - configMap:
            name: lunar-gateway-path-params
          name: path-params         
      {{- end }}

      {{- if .Values.configMapNames.root }}
        - configMap:
            name: {{ .Values.configMapNames.root }}
          name: root
      {{- else }}
        - configMap:
            name: lunar-gateway-root
          name: root
      {{- end }}

      {{- if .Values.secretNames.tlsCerts }}
        - secret:
            secretName: {{ .Values.secretNames.tlsCerts }}
          name: tls-certs
      {{- end }}
      {{- if .Values.secretNames.mtlsCerts }}
        - secret:
            secretName: {{ .Values.secretNames.mtlsCerts }}
          name: mtls-certs
      {{- end }}

      {{- else }} # i.e. lunarStreamsEnabled is false
      {{- if .Values.configMapNames.policies }}
        - configMap:
            items:
              - key: policies.yaml
                path: policies.yaml
            name: {{ .Values.configMapNames.policies }}
          name: policies      
      {{- else }}
        - configMap:
            items:
              - key: policies.yaml
                path: policies.yaml
            name: policies.yaml
          name: policies
      {{- end  }}
      {{- end }}
